### PR TITLE
 add collapse-rnaseq scripts

### PR DESCRIPTION
**Pull request by zhangb1**
## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

adding collapse-rnaseq scripts to the data assembly repo

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Environment:
* Test files:

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [ ] I have checked my code and corrected any misspellings
- [ ] I have committed any related changes to the PR

### CODE REVIEW

**Comment by zhangb1** [comment]
test file:

```
Rscript --vanilla 01-summarize_matrices.R -i pbta-gene-expression-rsem-tpm.polya.rds -g gencode.v27.primary_assembly.annotation.gtf.gz -m pbta-gene-expression-rsem-tpm-collapsed.polya.rds -t pbta-gene-expression-rsem-tpm-collapsed_table.polya.rds

Rscript --vanilla 01-summarize_matrices.R -i pbta-gene-expression-rsem-tpm.stranded.rds -g gencode.v27.primary_assembly.annotation.gtf.gz -m pbta-gene-expression-rsem-tpm-collapsed.stranded.rds -t pbta-gene-expression-rsem-tpm-collapsed_table.stranded.rds

```

**Review by komalsrathi — APPROVED** [review]
This looks in accordance with OpenPBTA scripts.

**Comment by zhangb1** [comment]
This input files are from the output in #2

**Review by HuangXiaoyan0106 — APPROVED** [review]
This looks good, tested scripts locally.

**Pull request merged**
